INSERT INTO POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS) VALUES (1,'Fisherman','REF0001','http://www.google.com',1,'2024-05-01','The Lobster Shop','Wilmington, NC','2024-05-02','Applied');

INSERT INTO POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS) VALUES (2,'Pilot','R0001121','http://www.google.com',1,'2024-05-03','The Lobster Liquidators','Wilmington, NC','2024-05-05','Rejected');

INSERT INTO POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS) VALUES (3,'Mechanic','P0023','http://www.google.com',1,'2024-05-05','The Lobster Claw','Wilmington, NC',NULL,'Pending');
