INSERT INTO APPLICATION (APP_ID, APP_DATE, APP_STATUS) VALUES (1,'2024-05-01','applied');
INSERT INTO POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_RANK, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_ID) VALUES (1,'Fisherman','REF0001','1','2024-05-01','The Lobster Shop','Wilmington, NC',1);

INSERT INTO APPLICATION (APP_ID, APP_DATE, APP_STATUS) VALUES (2,'2024-05-05','rejected');
INSERT INTO POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_RANK, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_ID) VALUES (2,'Pilot','R0001121','1','2024-05-03','The Lobster Liquidators','Wilmington, NC',2);

INSERT INTO APPLICATION (APP_ID, APP_DATE, APP_STATUS) VALUES (3,NULL,'pending');
INSERT INTO POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_RANK, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_ID) VALUES (3,'Mechanic','P0023','1','2024-05-05','The Lobster Claw','Wilmington, NC',3);
