CREATE TABLE APPLICATION(
  APP_ID BIGSERIAL PRIMARY KEY,
  APP_DATE DATE,
  APP_STATUS VARCHAR(10),
  POSTING_ID BIGINT NOT NULL
);


CREATE TABLE POSTING(
  POSTING_ID BIGSERIAL PRIMARY KEY,
  POSTING_NAME VARCHAR(64),
  POSTING_REF VARCHAR(20),
  POSTING_RANK VARCHAR(10),
  POSTING_DATE DATE,
  COMPANY_NAME VARCHAR(64),
  COMPANY_ADDRESS VARCHAR(128)
);

ALTER TABLE APPLICATION ADD FOREIGN KEY (POSTING_ID) REFERENCES POSTING(POSTING_ID);
CREATE INDEX IDX_POSTING_DATE_ ON POSTING(POSTING_DATE);
CREATE INDEX IDX_APP_DATE_ ON APPLICATION(APP_DATE);
