CREATE SCHEMA IF NOT EXISTS JOB;

CREATE TABLE IF NOT EXISTS JOB.POSTING(
  POSTING_ID BIGSERIAL PRIMARY KEY,
  POSTING_NAME VARCHAR(64),
  POSTING_REF VARCHAR(20),
  POSTING_URL VARCHAR(128),
  POSTING_PRIORITY BIGINT,
  POSTING_DATE VARCHAR(10),
  COMPANY_NAME VARCHAR(64),
  COMPANY_ADDRESS VARCHAR(64),
  APP_DATE VARCHAR(10),
  APP_STATUS VARCHAR(10),
  APP_STATUS_URL VARCHAR(128)
);

CREATE INDEX IF NOT EXISTS IDX_POSTING_DATE_ ON JOB.POSTING(POSTING_DATE);
CREATE INDEX IF NOT EXISTS IDX_APP_DATE_ ON JOB.POSTING(APP_DATE);



INSERT INTO JOB.POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS, APP_STATUS_URL) 
	VALUES (1,'Fisherman','REF0001','http://www.google.com',1,'2024-05-01','The Lobster Shop','Wilmington, NC','2024-05-02','Applied','http://joblookup.com');

INSERT INTO JOB.POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS, APP_STATUS_URL) 
	VALUES (2,'Pilot','R0001121','http://www.google.com',1,'2024-05-03','The Lobster Liquidators','Wilmington, NC','2024-05-05','Rejected','http://joblookup.com');

INSERT INTO JOB.POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS, APP_STATUS_URL) 
	VALUES (3,'Mechanic','P0023','http://www.google.com',1,'2024-05-05','The Lobster Claw','Wilmington, NC',NULL,'Pending',NULL);

INSERT INTO JOB.POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS, APP_STATUS_URL) 
	VALUES (4,'Professional Fish Cleaner','PFC002','http://www.surfcity.com',1,'2024-05-06','No Lobsters Allowed','Surf City, NC',NULL,'Pending',NULL);
	
INSERT INTO JOB.POSTING (POSTING_ID, POSTING_NAME, POSTING_REF, POSTING_URL, POSTING_PRIORITY, POSTING_DATE,COMPANY_NAME,COMPANY_ADDRESS,APP_DATE, APP_STATUS, APP_STATUS_URL) 
	VALUES (5,'Apprentice Fish Cleaner','PFC001','http://www.surfcity.com',2,'2024-05-06','No Lobsters Allowed','Surf City, NC',NULL,'Pending',NULL);
		